# Runs on push to main, basically the "release" version since we don't really do releases (that's bad right)
name: Cargo Build

on:
  - push
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            file-name: templatr
            prefix: linux

          # - os: macOS-latest
          #   file-name: templatr
          #   prefix: macos

          # - os: windows-latest
          #   file-name: templatr.exe
          #   prefix: windows

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get libdbus if Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y libdbus-1-dev

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.prefix }}-${{ matrix.file-name }}
          path: ./target/release/${{ matrix.file-name }}
          if-no-files-found: error